-- Tiraji — initial schema
-- Run in the Supabase SQL Editor (Dashboard → SQL Editor → New query → paste → Run),
-- or via the Supabase CLI (`supabase db push`).

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists pg_trgm; -- fuzzy search (Georgian + Latin)

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type listing_type as enum ('sale', 'swap', 'giveaway');
exception when duplicate_object then null; end $$;

do $$ begin
  create type book_condition as enum ('new', 'like_new', 'good', 'worn');
exception when duplicate_object then null; end $$;

do $$ begin
  create type listing_status as enum ('active', 'closed', 'hidden');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Helper: is the current user an admin? (SECURITY DEFINER avoids RLS recursion)
-- ---------------------------------------------------------------------------
-- (Defined after profiles exists; see below.)

-- ---------------------------------------------------------------------------
-- profiles  (1:1 with auth.users)
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  city         text,
  phone        text,
  show_phone   boolean not null default false,
  avatar_path  text,
  is_admin     boolean not null default false,
  created_at   timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from profiles where id = auth.uid()), false);
$$;

-- Auto-create a profile row whenever a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Public, privacy-safe view of a seller (hides phone unless show_phone = true).
create or replace view public_seller as
  select
    id,
    display_name,
    city,
    avatar_path,
    show_phone,
    case when show_phone then phone else null end as phone,
    created_at
  from profiles;

-- ---------------------------------------------------------------------------
-- genres  (small lookup, bilingual labels)
-- ---------------------------------------------------------------------------
create table if not exists genres (
  id      integer generated by default as identity primary key,
  slug    text unique not null,
  name_ka text not null,
  name_en text not null
);

insert into genres (slug, name_ka, name_en) values
  ('fiction',      'მხატვრული',        'Fiction'),
  ('nonfiction',   'არამხატვრული',      'Non-fiction'),
  ('poetry',       'პოეზია',            'Poetry'),
  ('children',     'საბავშვო',          'Children'),
  ('academic',     'აკადემიური',        'Academic'),
  ('history',      'ისტორია',           'History'),
  ('sci-tech',     'მეცნიერება & ტექ.', 'Science & Tech'),
  ('religion',     'რელიგია',           'Religion'),
  ('art',          'ხელოვნება',         'Art'),
  ('other',        'სხვა',              'Other')
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- listings
-- ---------------------------------------------------------------------------
create table if not exists listings (
  id                 uuid primary key default gen_random_uuid(),
  seller_id          uuid not null references profiles (id) on delete cascade,
  listing_type       listing_type not null,
  title              text not null,
  author             text,
  description        text,
  condition          book_condition,
  price              numeric(10, 2),        -- sale only; null otherwise
  is_negotiable      boolean not null default false,
  swap_wanted        text,                  -- what the owner wants in return (swap)
  currency           text not null default 'GEL',
  city               text,
  book_language      text,
  genre_id           integer references genres (id) on delete set null,
  isbn               text,
  cover_image_paths  text[] not null default '{}',
  cover_external_url text,                  -- Google Books fallback when no photos
  status             listing_status not null default 'active',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  -- combined text used for trigram search
  search_text        text generated always as (
    coalesce(title, '') || ' ' || coalesce(author, '')
  ) stored
);

create index if not exists listings_search_trgm  on listings using gin (search_text gin_trgm_ops);
create index if not exists listings_type_status   on listings (listing_type, status);
create index if not exists listings_created_at     on listings (created_at desc);
create index if not exists listings_city           on listings (city);
create index if not exists listings_genre          on listings (genre_id);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists listings_touch on listings;
create trigger listings_touch before update on listings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- book_alerts  (email-only subscriptions; no in-app notification)
-- ---------------------------------------------------------------------------
create table if not exists book_alerts (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles (id) on delete cascade,
  title      text,
  author     text,
  isbn       text,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  constraint book_alerts_has_criteria check (
    coalesce(title, '') <> '' or coalesce(author, '') <> '' or coalesce(isbn, '') <> ''
  )
);
create index if not exists book_alerts_active on book_alerts (active);

-- ---------------------------------------------------------------------------
-- conversations & messages
-- ---------------------------------------------------------------------------
create table if not exists conversations (
  id         uuid primary key default gen_random_uuid(),
  listing_id uuid references listings (id) on delete set null,
  buyer_id   uuid not null references profiles (id) on delete cascade,
  seller_id  uuid not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (listing_id, buyer_id)
);
create index if not exists conversations_buyer  on conversations (buyer_id);
create index if not exists conversations_seller on conversations (seller_id);

create table if not exists messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references conversations (id) on delete cascade,
  sender_id       uuid not null references profiles (id) on delete cascade,
  body            text not null,
  read_at         timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists messages_conversation on messages (conversation_id, created_at);

-- ---------------------------------------------------------------------------
-- notifications  (in-app bell: new messages only)
-- ---------------------------------------------------------------------------
create table if not exists notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles (id) on delete cascade,
  type       text not null,               -- 'new_message'
  payload    jsonb not null default '{}',
  read_at    timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user on notifications (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- favorites & reports
-- ---------------------------------------------------------------------------
create table if not exists favorites (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles (id) on delete cascade,
  listing_id uuid not null references listings (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, listing_id)
);

create table if not exists reports (
  id          uuid primary key default gen_random_uuid(),
  reporter_id uuid references profiles (id) on delete set null,
  listing_id  uuid not null references listings (id) on delete cascade,
  reason      text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table profiles      enable row level security;
alter table listings      enable row level security;
alter table book_alerts   enable row level security;
alter table conversations enable row level security;
alter table messages      enable row level security;
alter table notifications enable row level security;
alter table favorites     enable row level security;
alter table reports       enable row level security;

-- profiles: read own; admins read all. Public seller info comes from public_seller view.
drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles
  for select using (auth.uid() = id or public.is_admin());
drop policy if exists profiles_update on profiles;
create policy profiles_update on profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists profiles_insert on profiles;
create policy profiles_insert on profiles
  for insert with check (auth.uid() = id);

-- listings: anyone sees active; owner sees own; admins see all.
drop policy if exists listings_select on listings;
create policy listings_select on listings
  for select using (status = 'active' or seller_id = auth.uid() or public.is_admin());
drop policy if exists listings_insert on listings;
create policy listings_insert on listings
  for insert with check (seller_id = auth.uid());
drop policy if exists listings_update on listings;
create policy listings_update on listings
  for update using (seller_id = auth.uid() or public.is_admin());
drop policy if exists listings_delete on listings;
create policy listings_delete on listings
  for delete using (seller_id = auth.uid() or public.is_admin());

-- book_alerts: fully private to the owner.
drop policy if exists book_alerts_all on book_alerts;
create policy book_alerts_all on book_alerts
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- conversations: only the two parties (or admin).
drop policy if exists conversations_select on conversations;
create policy conversations_select on conversations
  for select using (buyer_id = auth.uid() or seller_id = auth.uid() or public.is_admin());
drop policy if exists conversations_insert on conversations;
create policy conversations_insert on conversations
  for insert with check (buyer_id = auth.uid());

-- messages: readable/insertable only by conversation parties.
drop policy if exists messages_select on messages;
create policy messages_select on messages
  for select using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );
drop policy if exists messages_insert on messages;
create policy messages_insert on messages
  for insert with check (
    sender_id = auth.uid()
    and exists (
      select 1 from conversations c
      where c.id = conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );
drop policy if exists messages_update on messages;
create policy messages_update on messages
  for update using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- notifications: private to the owner.
drop policy if exists notifications_select on notifications;
create policy notifications_select on notifications
  for select using (user_id = auth.uid());
drop policy if exists notifications_update on notifications;
create policy notifications_update on notifications
  for update using (user_id = auth.uid());

-- favorites: private to the owner.
drop policy if exists favorites_all on favorites;
create policy favorites_all on favorites
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- reports: any signed-in user can file; only admins can read.
drop policy if exists reports_insert on reports;
create policy reports_insert on reports
  for insert with check (auth.uid() is not null);
drop policy if exists reports_select on reports;
create policy reports_select on reports
  for select using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Search RPC — fuzzy (trigram) + filters + sort. Respects RLS (SECURITY INVOKER).
-- ---------------------------------------------------------------------------
create or replace function public.search_listings(
  q            text default null,
  p_type       listing_type default null,
  p_city       text default null,
  p_min_price  numeric default null,
  p_max_price  numeric default null,
  p_condition  book_condition default null,
  p_language   text default null,
  p_genre      integer default null,
  p_sort       text default 'recent',   -- recent | price_asc | price_desc | relevance
  p_limit      integer default 24,
  p_offset     integer default 0
)
returns setof listings
language sql
stable
as $$
  select *
  from listings l
  where l.status = 'active'
    and (p_type is null or l.listing_type = p_type)
    and (p_city is null or l.city = p_city)
    and (p_condition is null or l.condition = p_condition)
    and (p_language is null or l.book_language = p_language)
    and (p_genre is null or l.genre_id = p_genre)
    and (p_min_price is null or l.price >= p_min_price)
    and (p_max_price is null or l.price <= p_max_price)
    and (
      q is null or q = ''
      or l.search_text ilike '%' || q || '%'
      or l.search_text % q
    )
  order by
    case when p_sort = 'price_asc'  then l.price end asc  nulls last,
    case when p_sort = 'price_desc' then l.price end desc nulls last,
    case when p_sort = 'relevance' and q is not null and q <> ''
         then similarity(l.search_text, q) end desc nulls last,
    l.created_at desc
  limit greatest(p_limit, 1)
  offset greatest(p_offset, 0);
$$;

-- ---------------------------------------------------------------------------
-- Storage: public 'covers' bucket for listing photos
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('covers', 'covers', true)
on conflict (id) do nothing;

-- Anyone can view cover images; owners manage files under a folder named by their uid.
drop policy if exists covers_public_read on storage.objects;
create policy covers_public_read on storage.objects
  for select using (bucket_id = 'covers');

drop policy if exists covers_owner_insert on storage.objects;
create policy covers_owner_insert on storage.objects
  for insert with check (
    bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists covers_owner_update on storage.objects;
create policy covers_owner_update on storage.objects
  for update using (
    bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists covers_owner_delete on storage.objects;
create policy covers_owner_delete on storage.objects
  for delete using (
    bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text
  );
